# Site
name: iandanforth.github.io
time: 2018
description: Ian Danforth's Blog Thingamagigger
meta_description: "A log of ones thoughts, as one does."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
paginate: 15
baseurl: /

# Authors
authors:
  ian:
    name: Ian
    display_name: Ian
    email: iandanforth@gmail.com
    web: https://www.iandanforth.com
    twitter: https://twitter.com/iandanforth
    description: "Me."
 
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge